version: '3.8'

services:
  # Service Base de données
  db:
    image: mysql:5.7
    container_name: students-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: STUDENTS
    volumes:
      # On monte le fichier init.sql pour qu'il s'exécute au démarrage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # (Optionnel) Pour garder les données même si on coupe le conteneur
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Service Application Web
  web:
    build: .  # Construit l'image depuis le Dockerfile à la racine
    container_name: students-app
    restart: always
    ports:
      - "8088:3000"   # Port 3000 du conteneur -> 8088 sur EC2
    environment:
      - APP_DB_HOST=db
      - APP_DB_USER=nodeapp
      - APP_DB_PASSWORD=student12
      - APP_DB_NAME=STUDENTS
      - APP_PORT=3000
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
