version: '3.8'

services:
  # Service Base de données
  db:
    image: mysql:5.7  # On utilise la 5.7 pour être stable avec le vieux code du TP
    container_name: students-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: STUDENTS
    volumes:
      # On monte le fichier init.sql pour qu'il s'exécute au démarrage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # (Optionnel) Pour garder les données même si on coupe le conteneur
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Service Application Web
  web:
    build: .  # Construit l'image à partir du Dockerfile dans ce dossier
    container_name: students-app
    restart: always # Si l'app plante (car la DB n'est pas prête), elle redémarre
    ports:
      - "8088:80"   # Port 80 de ta machine -> Port 80 du conteneur
    environment:
      # C'est ici qu'on injecte les variables du script original
      - APP_DB_HOST=db       # "db" est le nom du service ci-dessus (DNS magique Docker)
      - APP_DB_USER=nodeapp
      - APP_DB_PASSWORD=student12
      - APP_DB_NAME=STUDENTS
      - APP_PORT=80
    depends_on:
      - db  # Attend que le service DB soit lancé
    networks:
      - app-network

# Création d'un réseau privé pour qu'ils communiquent entre eux
networks:
  app-network:

# Création du volume de stockage
volumes:
  db_data: